core/urls.py
from django.urls import include, path

from . import views
from core.views import core, admin, regular

urlpatterns = [
    path("", core.home, name="home"),
    path("", core.WelcomeView.as_view(), name="welcome"),
    path("welcome", core.WelcomeView.as_view(), name="welcome"),
    path("accounts/", include('django.contrib.auth.urls')),
    path("accounts/signup", core.SignUpView.as_view(), name="signup"),
    path("accounts/signup/admin", admin.AdminSignUpView.as_view(), name="admin-signup"),
    path("accounts/signup/regular", regular.RegularSignUpView.as_view(), name="regular-signup"),
]

quotecentre/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('', include("customer.urls")),
    path('', include("quote.urls")),
    path('', include("surveyor.urls")),
    path('', include("django.contrib.auth.urls")),
]

surveyor/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("surveyor/", views.SurveyorListView.as_view(), name="surveyor-list"),
    path("surveyor/add", views.SurveyorAddView.as_view(), name="surveyor-add"),
    path("surveyor/<slug:slug>", views.SurveyorDetailView.as_view(), name="surveyor-detail"),
    path("surveyor/<slug:slug>/delete", views.SurveyorDeleteView.as_view(), name="surveyor-delete"),
    path("surveyor/<slug:slug>/update", views.SurveyorUpdateView.as_view(), name="surveyor-update"),
    path("surveyor/<slug:slug>/addquote", views.SurveyorAddQuoteView.as_view(), name="surveyor-add-quote"),
]

quote/models.py
from django.db import models
from django.db.models import Sum
from django.core.validators import MinValueValidator
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from customer.models import Customer
from surveyor.models import Surveyor

# Create your models here.

class Quote(models.Model):
    reference = models.CharField(max_length=50)
    class SystemType(models.TextChoices):
        INTRUDER_ALARM = "IA", _("Intruder Alarm")
        FIRE_ALARM = "FA", _("Fire Alarm")
        ACCESS_CONTROL = "AC", _("Access Control")
        CCTV = "CC", _("CCTV System")
        FIRE_EXTINGUISHERS = "FE", _("Fire Extinguishers")
        OTHER = "OT", _("Other")
    system_type = models.CharField(
        max_length = 2,
        choices = SystemType.choices,
        default = SystemType.INTRUDER_ALARM,
    )
    description = models.TextField(blank=True)
    class PremisesType(models.TextChoices):
        DOMESTIC = "DO", _("Domestic System")
        COMMERCIAL = "CO", _("Commercial System")
        OTHER = "OT", _("Other")
    premises_type = models.CharField(
        max_length = 2,
        choices = PremisesType.choices,
        default = PremisesType.COMMERCIAL,
    )
    class Status(models.TextChoices):
        OPEN = "OP", _("Open")
        CLOSED = "CL", _("Closed")
        CONVERTED = "CO", _("Converted")
    quote_status = models.CharField(
        max_length = 2,
        choices = Status.choices,
        default = Status.OPEN,
    )
    remarks = models.CharField(max_length=320, blank=True)
    creation_date = models.DateField(auto_now_add=True)
    quotation_date = models.DateField()
    valid_until = models.DateField()
    last_modified = models.DateField(auto_now=True)
    quote_sale_value = models.DecimalField(
        max_digits = 19,
        decimal_places = 2,
        validators = [MinValueValidator(0.00)]
    )
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name="quotes")
    surveyor = models.ForeignKey(Surveyor, null=True, on_delete=models.SET_NULL, related_name="quotes")
    
    def get_absolute_url(self):
        return reverse("quote-detail", args=[self.id])

    def __str__(self):
        return "%s (id: %s, customer: %s)" %(self.reference, self.id, self.customer.name,)

surveyor/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from core.utils import unique_slug_generator

# Create your models here.

class Surveyor(models.Model):
    slug = models.SlugField(null = False, unique = True)
    name = models.CharField(max_length=100)
    class SalesRegion(models.TextChoices):
        SCOTLAND = "SC", _("Scotland")
        NORTHERN_IRELAND = "NI", _("Northern Ireland")
        NORTH_EAST = "NE", _("North East")
        NORTH_WEST = "NW", _("North West")
        EAST_MIDLANDS = "EM", _("East Midlands")
        WEST_MIDLANDS = "WM", _("West Midlands")
        WALES = "WA", _("Wales")
        SOUTH_WEST = "SW", _("South West")
        SOUTH_EAST = "SE", _("South East")
        GREATER_LONDON = "GL", _("Greater London")
    sales_region = models.CharField(
        max_length = 2,
        choices = SalesRegion.choices,
        default = SalesRegion.GREATER_LONDON,
    )
    telephone_no = models.CharField(max_length=20)
    mobile_no = models.CharField(max_length=20, blank=True)
    alt_telephone_no = models.CharField(max_length=20, blank=True)
    email_address = models.EmailField(max_length=254, blank=True)

    def get_absolute_url(self):
        return reverse("surveyor-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return "%s (id: %s)" %(self.name, self.slug,)
        

def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender=Surveyor)

surveyor/forms.py
from django.forms import ModelForm

from .models import Surveyor

class SurveyorForm(ModelForm):
    class Meta:
        model = Surveyor
        # fields = "__all__"
        exclude = ["slug"]
        labels = {
            "name": "Name",
            "sales_region": "Sales Region",
            "telephone_no": "Telephone No.",
            "mobile_no": "Mobile No.",
            "alt_telephone_no": "Alternate Telephone No.",
            "email_address": "eMail Address",
        }
        error_messages = {
            "name": {
                "required": "Please enter a surveyor name",
                "max_length": "Please enter a shorter surveyor name"
            }
        }

surveyor/views.py
from django.views.generic import DetailView, ListView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from .forms import SurveyorForm
from .models import Surveyor
from quote.forms import QuoteAddFromSurveyorForm
from quote.models import Quote
from core.decorators import admin_required

# Create your views here.

class SurveyorListView(LoginRequiredMixin, ListView):
    template_name = "surveyor/surveyor-list.html"
    model = Surveyor
    context_object_name = "surveyors"

class SurveyorDetailView(LoginRequiredMixin, DetailView):
    template_name = "surveyor/surveyor-detail.html"
    model = Surveyor
    slug_url_kwarg = 'slug'
    slug_field = 'slug'

class SurveyorAddView(LoginRequiredMixin, CreateView):
    model = Surveyor
    form_class = SurveyorForm
    template_name = "surveyor/surveyor-add.html"
    success_url = "/surveyor"

@method_decorator([admin_required], name='dispatch')
class SurveyorDeleteView(LoginRequiredMixin, DeleteView):
    model = Surveyor
    template_name = "surveyor/surveyor-delete.html"
    success_url = "/surveyor"
    
class SurveyorUpdateView(LoginRequiredMixin, UpdateView):
    model = Surveyor
    form_class = SurveyorForm
    template_name = "surveyor/surveyor-add.html"
    success_url = "/surveyor"

class SurveyorAddQuoteView(LoginRequiredMixin, CreateView):
    model = Quote
    form_class = QuoteAddFromSurveyorForm
    template_name = "quote/quote-add-from-surveyor.html"
    success_url = "/surveyor"
    

    def get_success_url(self):
        surveyor_slug=self.kwargs['slug']
        return reverse_lazy('surveyor-detail', kwargs={'slug': surveyor_slug})

    def form_valid(self, form):
        form.instance.surveyor_slug = self.kwargs["slug"]
        return super().form_valid(form)

surveyor/templates/surveyor/surveyor-add.html
{% extends "core/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h2>Add Surveyor</h2>
  <form method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-6">
            {{ form.name|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ form.sales_region|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            {{ form.telephone_no|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ form.mobile_no|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            {{ form.alt_telephone_no|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ form.email_address|as_crispy_field }}
        </div>
    </div>
    <button type="submit" class="btn btn-success">Save Surveyor</button><a class="btn btn-danger" href='/surveyor'>Cancel</a>
  </form>
{% endblock %}

surveyor/templates/surveyor/surveyor-delete.html
{% extends "core/base.html" %}

{% block content %}

<form method='POST'>
    {% csrf_token %}
        <h1>Do you want to delete surveyor {{ surveyor.name }}?</h1>
        <p><input class="btn btn-danger" type='submit' value='Yes' /><a class="btn btn-secondary" href="{% url "surveyor-list" %}">Cancel</a></p>
</form>
{% endblock %}

surveyor/templates/surveyor/surveyor-detail.html
{% extends "core/base.html" %}

{% block title %}Surveyor Details{% endblock %}

{% block content %}
    <h1>{{ surveyor.name }}</h1>
    <div class="row">
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Surveyor Details</h5>
                <small class="text-muted">Unique Id</small>
                <p class="card-text">{{ surveyor.slug }}</p>
                <small class="text-muted">Sales Region</small>
                <p class="card-text">{{ surveyor.get_sales_region_display }}</p>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Contact Details</h5>
              <small class="text-muted">Telephone No.</small>
              <p class="card-text">{{ surveyor.telephone_no }}</p>
              <small class="text-muted">Mobile No.</small>
              <p class="card-text">{{ surveyor.mobile_no }}</p>
              <small class="text-muted">Alternate Telephone No.</small>
              <p class="card-text">{{ surveyor.alt_telephone_no }}</p>
              <small class="text-muted">eMail Address</small>
              <p class="card-text">{{ surveyor.email_address }}</p>
            </div>
          </div>
        </div>
      </div>
    
    {% if surveyor.quotes.count > 0 %}
    <h4>Quotes for {{ surveyor.name }}</h4>
    <table class="table table-striped">
      <thead>
          <tr>
              <th scope="col">#</th>
              <th scope="col">Customer Name</th>
              <th scope="col">System Type</th>
              <th scope="col">Premises Type</th>
              <th scope="col">Status</th>
              <th scope="col" class="text-end">Sale Value</th>
              <th scope="col" class="text-end">Action</th>
          </tr>
      </thead>
      <tbody>
          {% for quote in surveyor.quotes.all %}
          <tr>
              <th scope="row">{{ quote.id }}</th>
              <td>{{ quote.customer.name }}</td>
              <td>{{ quote.get_system_type_display }}</td>
              <td>{{ quote.get_premises_type_display }}</td>
              <td>{{ quote.get_quote_status_display }}</td>
              <td class="text-end">£{{ quote.quote_sale_value }}</td>
              <td class="text-end"><a class="btn btn-primary" href="{{ quote.get_absolute_url }}" role="button">View</a></td>
          </tr>
          {% endfor %}
          <tr>
              <th scope="row">Total</th>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td class="text-end">£{{ quotes.calculated_total }}</td>
              <td class="text-end"></td>
          </tr>
      </tbody>
  </table>
    {% else %}
        <p>There are no surveyors to display</p>
    {% endif %}
    <a class="btn btn-primary" href="{% url "surveyor-list" %}" role="button">Go Back</a>
    <a class="btn btn-primary" href="{{ surveyor.get_absolute_url }}/update" role="button">Update Surveyor</a>
    <a class="btn btn-danger" href="{{ surveyor.get_absolute_url }}/delete" role="button">Delete Surveyor</a>
    <a class="btn btn-secondary" href="{{ surveyor.get_absolute_url }}/addquote" role="button">Add Quote</a>
{% endblock %}

surveyor/templates/surveyor/surveyor-list.html
{% extends "core/base.html" %}

{% block title %}Surveyor List{% endblock %}

{% block content %}
<h2>Surveyor List</h2>
{% if surveyors %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Unique Id</th>
                    <th scope="col">Surveyor Name</th>
                    <th scope="col">Sales Region</th>
                    <th scope="col">Mobile No.</th>
                    <th scope="col">eMail Address</th>
                    <th scope="col" class="text-end">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for surveyor in surveyors %}
                <tr>
                    <th scope="row">{{ surveyor.slug }}</th>
                    <td>{{ surveyor.name }}</td>
                    <td>{{ surveyor.get_sales_region_display }}</td>
                    <td>{{ surveyor.mobile_no }}</td>
                    <td>{{ surveyor.email_address }}</td>
                    <td class="text-end"><a class="btn btn-primary" href="{{ surveyor.get_absolute_url }}" role="button">View</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are currently no surveyors in the database</p>
    {% endif %}
    <a class="btn btn-primary" href="/surveyor/add" role="button">Add Surveyor</a>
{% endblock %}